//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: HelloAnnotation.java
//

#include "HelloAnnotation.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/io/PrintStream.h"
#include "java/lang/System.h"

@interface HelloAnnotation ()

+ (void)getSomething;

@end

__attribute__((unused)) static void HelloAnnotation_getSomething();

@implementation HelloAnnotation

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  HelloAnnotation_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)mainWithNSStringArray:(IOSObjectArray *)args {
  HelloAnnotation_mainWithNSStringArray_(args);
}

+ (void)getSomething {
  HelloAnnotation_getSomething();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0xa, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(mainWithNSStringArray:);
  methods[2].selector = @selector(getSomething);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "main", "[LNSString;" };
  static const J2ObjcClassInfo _HelloAnnotation = { "HelloAnnotation", NULL, ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_HelloAnnotation;
}

@end

void HelloAnnotation_init(HelloAnnotation *self) {
  NSObject_init(self);
}

HelloAnnotation *new_HelloAnnotation_init() {
  J2OBJC_NEW_IMPL(HelloAnnotation, init)
}

HelloAnnotation *create_HelloAnnotation_init() {
  J2OBJC_CREATE_IMPL(HelloAnnotation, init)
}

void HelloAnnotation_mainWithNSStringArray_(IOSObjectArray *args) {
  HelloAnnotation_initialize();
  [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithNSString:@"Hello Annotation."];
  for (jint i = 0; i < 100; i++) {
    @autoreleasepool {
      HelloAnnotation_getSomething();
    }
  }
}

void HelloAnnotation_getSomething() {
  @autoreleasepool {
    HelloAnnotation_initialize();
    [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printWithNSString:@"getSomething"];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(HelloAnnotation)
