//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: HelloWeakAnnotation.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_HelloWeakAnnotation")
#ifdef RESTRICT_HelloWeakAnnotation
#define INCLUDE_ALL_HelloWeakAnnotation 0
#else
#define INCLUDE_ALL_HelloWeakAnnotation 1
#endif
#undef RESTRICT_HelloWeakAnnotation

#if !defined (HelloWeakAnnotation_) && (INCLUDE_ALL_HelloWeakAnnotation || defined(INCLUDE_HelloWeakAnnotation))
#define HelloWeakAnnotation_

@class IOSObjectArray;
@protocol JavaUtilList;

@interface HelloWeakAnnotation : NSObject {
 @public
  __unsafe_unretained id<JavaUtilList> kingTest_;
}

#pragma mark Public

- (instancetype)init;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

@end

J2OBJC_EMPTY_STATIC_INIT(HelloWeakAnnotation)

FOUNDATION_EXPORT void HelloWeakAnnotation_init(HelloWeakAnnotation *self);

FOUNDATION_EXPORT HelloWeakAnnotation *new_HelloWeakAnnotation_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT HelloWeakAnnotation *create_HelloWeakAnnotation_init();

FOUNDATION_EXPORT void HelloWeakAnnotation_mainWithNSStringArray_(IOSObjectArray *args);

J2OBJC_TYPE_LITERAL_HEADER(HelloWeakAnnotation)

#endif

#pragma pop_macro("INCLUDE_ALL_HelloWeakAnnotation")
