//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: WeakRefDemo.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_WeakRefDemo")
#ifdef RESTRICT_WeakRefDemo
#define INCLUDE_ALL_WeakRefDemo 0
#else
#define INCLUDE_ALL_WeakRefDemo 1
#endif
#undef RESTRICT_WeakRefDemo

#if !defined (WeakRefDemo_) && (INCLUDE_ALL_WeakRefDemo || defined(INCLUDE_WeakRefDemo))
#define WeakRefDemo_

@class IOSObjectArray;

@interface WeakRefDemo : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

@end

J2OBJC_EMPTY_STATIC_INIT(WeakRefDemo)

FOUNDATION_EXPORT void WeakRefDemo_init(WeakRefDemo *self);

FOUNDATION_EXPORT WeakRefDemo *new_WeakRefDemo_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT WeakRefDemo *create_WeakRefDemo_init();

FOUNDATION_EXPORT void WeakRefDemo_mainWithNSStringArray_(IOSObjectArray *args);

J2OBJC_TYPE_LITERAL_HEADER(WeakRefDemo)

#endif

#if !defined (WeakRefDemo_Demo_) && (INCLUDE_ALL_WeakRefDemo || defined(INCLUDE_WeakRefDemo_Demo))
#define WeakRefDemo_Demo_

@class WeakRefDemo;

@interface WeakRefDemo_Demo : NSObject

#pragma mark Public

- (instancetype)initWithWeakRefDemo:(WeakRefDemo *)outer$
                       withNSString:(NSString *)value;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(WeakRefDemo_Demo)

FOUNDATION_EXPORT void WeakRefDemo_Demo_initWithWeakRefDemo_withNSString_(WeakRefDemo_Demo *self, WeakRefDemo *outer$, NSString *value);

FOUNDATION_EXPORT WeakRefDemo_Demo *new_WeakRefDemo_Demo_initWithWeakRefDemo_withNSString_(WeakRefDemo *outer$, NSString *value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT WeakRefDemo_Demo *create_WeakRefDemo_Demo_initWithWeakRefDemo_withNSString_(WeakRefDemo *outer$, NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(WeakRefDemo_Demo)

#endif

#pragma pop_macro("INCLUDE_ALL_WeakRefDemo")
